default_platform(:ios)

platform :ios do
  lane :beta do
    match(
      type: "appstore",
      readonly: true,
      git_url: "git@github.com:beseendev/ios-certificates.git",
      verbose: true
    )

    build_app(
      workspace: "App.xcworkspace",
      scheme: "App",
      export_method: "app-store",
      clean: true
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end
