default_platform(:ios)

platform :ios do
  lane :beta do
    app_store_connect_api_key(
      key_id: ENV["APPSTORE_KEY_ID"],
      issuer_id: ENV["APPSTORE_ISSUER_ID"],
      key_content: ENV["APPSTORE_PRIVATE_KEY"],
      is_key_content_base64: false
    )

    match(
      type: "appstore",
      readonly: true,
      git_url: "git@github.com:beseendev/ios-certificates.git",
      app_identifier: "com.beseen.app.official",
      verbose: true
    )

    build_app(
      workspace: "App.xcworkspace",
      scheme: "App",
      configuration: "Release",
      export_method: "app-store",
      clean: true,
      xcargs: "CODE_SIGN_STYLE=Manual DEVELOPMENT_TEAM=HJR4R6DQV4 CODE_SIGN_IDENTITY='Apple Distribution' PROVISIONING_PROFILE_SPECIFIER='#{ENV["sigh_com.beseen.app.official_appstore_profile-name"]}'",
      export_options: {
        provisioningProfiles: {
          "com.beseen.app.official" => ENV["sigh_com.beseen.app.official_appstore_profile-name"]
        }
      }
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end
